efoucault/heliast2

app/models/user.rb
=> fixed syntax on association user

app/models/user.rb
=> fix syntax 2

app/controllers/options_controller.rb, app/views/options/_new.html.erb, app/views/options/new.html.erb, app/views/questions/show.html.erb, config/routes.rb, test/controllers/options_controller_test.rb
=> added option controller and views

app/assets/stylesheets/components/_option.scss, app/javascript/packs/application.js, app/views/questions/_option_fields.html.erb
=> added trash on new indecision

app/assets/stylesheets/components/_form_post.scss, app/assets/stylesheets/components/_option.scss, app/controllers/questions_controller.rb, app/javascript/packs/application.js, app/views/questions/_option_fields.html.erb, app/views/questions/new.html.erb
=> changed css on new indecision

app/views/questions/_question_cards.html.erb
=> changed categories on index but only the instance so far

app/assets/stylesheets/components/_option.scss
=> center index on new question

app/views/questions/new.html.erb
=> default value on resolution type

app/controllers/answers_controller.rb, app/models/question.rb, app/views/questions/show.html.erb
=> added render on question if no option selected

app/controllers/users_controller.rb, app/models/user.rb
=> added queries : score by category

app/controllers/answers_controller.rb
=> change question status when answer is submitted

app/javascript/packs/application.js, app/views/questions/new.html.erb
=> hide and show options

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_option.scss, app/assets/stylesheets/components/_thumbs.scss, app/controllers/users_controller.rb, app/models/user.rb, app/views/questions/new.html.erb, app/views/questions/show.html.erb, db/migrate/20180830132136_add_satisfied_to_questions.rb, db/schema.rb
=> fixed queries

app/assets/stylesheets/components/_thumbs.scss, app/controllers/questions_controller.rb, app/views/questions/show.html.erb
=> added satisfaction actions

app/views/questions/show.html.erb
=> hide options if title and pictures are empty

app/controllers/questions_controller.rb
=> changed redirection after question creation to question show

app/views/questions/show.html.erb
=> deleted edit button on question show

app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/views/pages/_podium.html.erb, app/views/pages/classement.html.erb
=> added 2 fixs on JS and ranking features

app/controllers/pages_controller.rb, app/views/pages/classement.html.erb
=> added ranking feature : it's working

app/views/pages/_podium.html.erb
=> fixed podium

db/seeds.rb
=> seedsphotos

app/views/pages/classement.html.erb
Normalement le classement ne présente plus les users de manière aléatoire. 
@off-batt
=> l'ordre dans le classement est désormais ok

app/assets/stylesheets/pages/_dashboard.scss, app/controllers/questions_controller.rb, app/views/questions/_question_cards.html.erb, app/views/questions/show.html.erb
J'ai aussi changé la couleur des statuts sur l'index à gris car ils restaient en turquoise jusque là. 
@off-batt
=> change status to closed when clicking on thumbs up or thumbs down

app/views/pages/_podium.html.erb, app/views/questions/_my_questions.html.erb
Le classement du podium était aussi dans le désordre, donc j'ai appliqué le même fix que sur le classement tout court
@off-batt
=> fixe podium ranking

app/views/questions/_question_cards.html.erb
=> on ne voit que les indecisions en attente de reponse dans l'index

app/assets/stylesheets/components/_option.scss, app/javascript/packs/application.js, app/views/questions/_option_fields.html.erb
=> added thumbnails on picutre upload

app/javascript/packs/application.js
=> afficher ou non le range selon le type de résolution

app/assets/stylesheets/components/_form_post.scss, app/javascript/packs/application.js, app/views/questions/new.html.erb
=> separation du form en 3, progresion 3 etapes, switch avant/apres possible

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/assets/javascripts/channels/notifications.js, app/assets/javascripts/notifications.js, app/channels/application_cable/connection.rb, app/channels/notifications_channel.rb, app/controllers/answers_controller.rb, app/controllers/notifications_controller.rb, app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/models/notification.rb, app/models/question.rb, app/models/user.rb, app/views/notifications/index.json.jbuilder, app/views/pages/notification.html.erb, app/views/questions/index.html.erb, app/views/shared/_navbar.html.erb, config/cable.yml, config/routes.rb, db/migrate/20180902023151_create_notifications.rb, db/migrate/20180902153530_add_actor_and_read_to_notifications.rb, db/schema.rb, test/controllers/notifications_controller_test.rb, test/models/notification_test.rb
notifs fonctionnelles dès qu'une réponse est apportée à sa question 
TODO : définir les différentes notifs que l'on souhaite
Le design c'est pas encore trop ça  :/
=> Notifications

app/assets/stylesheets/components/_banner.scss, app/javascript/packs/application.js, app/views/questions/index.html.erb
=> added banner and category filter

app/assets/javascripts/notifications.js, app/assets/stylesheets/components/_navbar.scss, app/controllers/notifications_controller.rb, app/models/notification.rb, app/views/notifications/answers/_answer.html.erb, app/views/notifications/index.json.jbuilder
=> improving notifs with red border left for unread notifs

app/javascript/packs/application.js
=> fix application.js

app/assets/stylesheets/components/_histogram.scss, app/assets/stylesheets/components/_index.scss, app/javascript/packs/application.js, app/views/questions/show.html.erb
@off-batt 
Reste à faire : 
- Ne l'afficher que si on est en mode Multi Héliastes
- Le mettre au même format que la réponse en mode mono héliaste
- Le rendre plus joli
- Ajouter le nombre de réponses
- Faire une animation sur la width (cf. MEM)
- Optimiser le code : boucle plutôt que 4 répétitions
=> ajout de l'histogramme en bas de la show d'une indécision

app/assets/stylesheets/components/_histogram.scss, app/views/answers/_multiheliast.html.erb, app/views/questions/show.html.erb
=> pleins de ptits trucs

app/assets/stylesheets/components/_commentaires.scss, app/assets/stylesheets/components/_index.scss, app/views/answers/_multiheliast.html.erb
=> added comments on histograms

app/assets/stylesheets/components/_option.scss, app/javascript/packs/application.js, app/views/questions/_option_fields.html.erb
=> added js to increase option height when preview loaded

app/assets/stylesheets/components/_option.scss
=> décaler l'image sur la droite

app/views/shared/_navbar.html.erb
=> j'ai enlevé les boutons de la navbar

app/views/pages/classement.html.erb
=> fixed classement

db/seeds.rb
=> seeds completees

app/views/pages/classement.html.erb
=> fix dimensjons

app/views/answers/_monoheliast.html.erb, app/views/questions/show.html.erb
=> cacher les divs moches

app/assets/stylesheets/components/_footer.scss, app/controllers/application_controller.rb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
=> fix bas de page + add loader on button signin and signup + fix pseudo

app/assets/images/add-active.svg, app/assets/images/add.svg, app/assets/images/alarme-active.svg, app/assets/images/alarme.svg, app/assets/images/classement-active.svg, app/assets/images/new-active.svg, app/assets/images/new.svg, app/assets/images/profil-active.svg, app/assets/images/social-active.svg, app/assets/images/social.svg, app/assets/images/trophe-active.svg, app/assets/images/trophe.svg, app/assets/stylesheets/components/_footer.scss
=> footer fixer

app/views/answers/_multiheliast.html.erb
=> if photo empty on comments multi heliast, display generic pic

app/assets/stylesheets/pages/_classement.scss, app/views/pages/classement.html.erb
=> correction du classement pour la 12eme fois

app/controllers/answers_controller.rb, app/controllers/questions_controller.rb, app/javascript/packs/application.js, app/views/answers/_new.html.erb, package.json, yarn.lock
=> add modal when submitting an answer

app/views/questions/new.html.erb
=> loader spinner when adding a new question and uploading pictures + space on bottom page

app/controllers/questions_controller.rb, app/models/question.rb, app/views/questions/new.html.erb
=> avoid 500 on question creation if mandatory fields are not filled

db/seeds.rb
reste les photos a ajouter et le classement a finaliser
=> 0509v2 avec question multi

app/views/questions/show.html.erb
=> changed order on question show

app/assets/stylesheets/components/_commentaires.scss, app/views/answers/_multiheliast.html.erb
=> changement de l'affichage des commentaire sur multi

app/views/layouts/application.html.erb
=> kevin astuce pour etre en mode appli mobile

app/controllers/answers_controller.rb, app/controllers/questions_controller.rb, app/views/notifications/answers/_answer.html.erb, app/views/notifications/index.json.jbuilder, app/views/notifications/questions/_feedback.html.erb
=> notification a l'héliaste lorsque l'indécis donne un feedback sur la décision

app/assets/stylesheets/components/_answer.scss, app/javascript/packs/application.js, app/views/answers/_monoheliast.html.erb, app/views/questions/_options_show.html.erb, app/views/questions/show.html.erb
=> affichage des options'

db/seeds.rb
=> Seeds0509v5

app/assets/stylesheets/pages/_historique.scss, app/views/notifications/answers/_answer.html.erb, app/views/notifications/questions/_feedback.html.erb, app/views/pages/historique.html.erb
=> changed a few things on notif display

app/controllers/questions_controller.rb, app/javascript/components/notifications.js, app/views/notifications/answers/_answer.html.erb, app/views/notifications/questions/_feedback.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb
+ supression des notifs depuis la navbar
=> le nbre de notif s'actualise depuis le footer lorsqu'on clique spécfiquement dessus

app/assets/stylesheets/pages/_historique.scss, app/javascript/components/notifications.js, app/javascript/packs/application.js, app/views/notifications/answers/_answer.html.erb, app/views/notifications/questions/_feedback.html.erb, app/views/shared/_footer.html.erb
with red bubble popping and disappearing when 0 notifs in real time
=> perfect notification comportement

app/javascript/packs/application.js, app/views/questions/new.html.erb
=> js corrigé sur le type de resolution

app/assets/stylesheets/pages/_dashboard.scss, app/assets/stylesheets/pages/_historique.scss, app/views/notifications/answers/_answer.html.erb, app/views/notifications/questions/_feedback.html.erb, app/views/users/show.html.erb
Online / offline pastilles sur notifs : 
Sur profil user :
=> Pastilles verte et rouge si l'user est connecté 

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/users/edit.html.erb
=> possibilité de mettre à jour son mot de passe depuis edit profil
